### List all messages
GET http://localhost:3000/messages


### Create new message
POST http://localhost:3000/messages
content-type: application/json

{
  "content": "Message After adding DI"
}


### Get message by Id: 
GET http://localhost:3000/messages/252